### ISSUE TITLE
The helper app is missing a link to the CEF framework

### ISSUE THREAD

**Issue by razvanilin** [michaelbaisch/ofxCef#2]
Hey, amazing work on getting this addon up and running. I just gave it a try on MacOS and I seem to make progress already 🍺 

I ran into an issue where the `Helper.app` couldn't find a link to the CEF framework and it was giving an error like this: `dyld: Library not loaded:`

I modified the Build Phases script to create a symlink to the framework in the main app. I basically added these two lines at the end of the script to make it work:

```
mkdir "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Frameworks/$PRODUCT_NAME Helper.app/Contents/Frameworks"
ln -s "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Frameworks/Chromium Embedded Framework.framework" "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Contents/Frameworks/$PRODUCT_NAME Helper.app/Contents/Frameworks"
```

**Comment by michaelbaisch** [comment]
I had a change that fixed that locally, didn't think it was important. Anyway, so the newest commit should fix this as well:

https://github.com/michaelbaisch/ofxCef/commit/7372d0ab285baa2de799882bf6045c9be2be680d
